### ISSUE TITLE
Deployment 503 Error

### ISSUE THREAD

**Issue by zhumingcheng697** [dulldesk/words-api#5]
The deployment on heroku suddenly stopped working either today or yesterday and is consistently giving 503 errors. The heroku page says that “An error occurred in the application and your page could not be served.”

**Comment by TaToTanWeb** [comment]
Same issue here :/ I'll use `https://dulldesk.github.io/words/{type}/{letter}-min.json` as a workaround for now.
For example: https://dulldesk.github.io/words/animals/a-min.json

**Comment by zhumingcheng697** [comment]
It appears that the issue has been resolved.
