### ISSUE TITLE
Wrong response

### ISSUE THREAD

**Issue by 6a6ydoping** [dulldesk/words-api#8]
When I request the https://random-word-form.herokuapp.com/random/noun?count=1000 I get 1000 words starting with the same letter in the output

**Comment by dulldesk** [comment]
In hindsight, I should have watched this repo more. Will address, thanks for bringing it up!

**Comment by dulldesk** [comment]
913533ad988f0e92435211dc394af202202cbc9b; once again, thanks for posting an issue!
